### ISSUE TITLE
Getting SSH Error after initial setup

### ISSUE THREAD

**Issue by motonuke** [salehmiri90/Esxi8u1_Automate_Installation-on-Baremetal#9]
After setting everything up and defining some hosts, I am getting an SSH error on:

TASK [copy-iso-mount : Mounting ISO & Copy to Directories]

msg": "Failed to connect to the host via ssh: ssh: Could not resolve hostname ilo-esxi: Name or service not known", "unreachable": true

The code doesn't seem to be using the right vars from host_vars to connect to SSH on the ilo ip address.

I'm also unsure why there is an SSH connection when this role is doing local work with the ISO.

**Comment by salehmiri90** [comment]
Hello Dear,
You have to setup a second server as stage role then the playbook will change over on stage server not ansible server.
